name = "digitelio-ai-worker"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "digitelio-db"
database_id = "0f4ad020-dc3c-45bd-8a88-baca0e2aec75"

# R2 sera activé au sprint suivant
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "digitelio-storage"

[vars]
ENVIRONMENT = "production"
